### PR TITLE
fix: 类型导出失败

### PR DESCRIPTION
**Pull request by huxinfeng**
* 模块"czg"没有导出的成员"UserConfig"

## Related ISSUE

> Input follow ISSUE URL address

## Type Of Change

- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 📝 Document (This change requires a documentation update)
- [ ] 🎨 Theme style (Theme style beautification)
- [ ] ⚠  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🔨 Workflow (Workflow changes)

## Clear Describe

> A clear and concise description of what update for target.

## Description

> Please enter detailed relevant motivation, background and implementation ... descriptive information.

## Test Case

> Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test case.

### CODE REVIEW

**Comment by Zhengqbbb** [comment]
emmm create a issue, and provide a reproduction example

可以创建一个issue，描述一下问题以及提供一个复现例子

image

**Comment by huxinfeng** [comment]
image

**Comment by Zhengqbbb** [comment]
> 我手动修改为node_module，为 index.d.ts，就可以识别

我已复现出来，今天之内处理完毕

**Comment by Zhengqbbb** [comment]
@huxinfeng 
LFG !~ Thank you for pointing out this issue and create this PR ~
I have merged into the main branch and released the `1.9.3-beta.1` pre-release version for testing.
You can use the following commands for testing.

```sh
npm  i -D czg@next
```

If there are any issues, please point them out.
I plan to release 1.9.4 tonight or tomorrow.

**Comment by Zhengqbbb** [comment]
The latest version 🌟(v1.9.3)🌟 should be resolve this issue request , please have a try. 💪
👀 Let me know if there are still any issues. 🎉

**Pull request merged**
