### PR TITLE
fix(cz-git): fix minor issues in default messages

### PR DESCRIPTION
**Pull request by jaklan**
## Type Of Change

- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 📝 Document (This change requires a documentation update)
- [ ] 🎨 Theme style (Theme style beautification)
- [ ] ⚠  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🔨 Workflow (Workflow changes)

## Clear Describe

fix(cz-git): fix minor issues in default messages

## Description

Fix a) missing word  b) accidentally connected messages c) casing d) redundant whitespace.

### CODE REVIEW

**Comment by jaklan** [comment]
@Zhengqbbb 
> Btw, Do you have any other thoughts on this pr?

Would you like to ask about anything specific? In general, I just wanted to fix the issue with:
`footerPrefixsSelect: "Select the ISSUES type of changeList by this change (optional):",`
because there were two messages merged by coincidence (`List by this change` comes from `footer` message), and I also saw a few minor issues with the other defaults so I corrected them by the way 😉

**Comment by Zhengqbbb** [comment]
> Would you like to ask about anything specific? 

@jaklan 
Yeah. `CLOSED`  is added, it may cause semantic problems.  it may be follow | wip | link 🤔.

**Comment by jaklan** [comment]
@Zhengqbbb that's a pretty good point, I also overwrite it to another value in my project 😄

I just used `CLOSED` because it is default message in `cz-customizable`:
https://github.com/leoforfree/cz-customizable/blob/master/questions.js#L66

and I wanted to keep the messages the same as there, but I agree it's confusing, so probably it's worth to make some improvement here.

What I personally use is:
`footer: "List any ISSUES AFFECTED by this change. E.g.: #31, #34:\n",`

**Comment by Zhengqbbb** [comment]
> What I personally use is: `footer: "List any ISSUES AFFECTED by this change. E.g.: #31, #34:\n",`

AFFECTED nice !

**Pull request merged**
