### PR TITLE
add option to set custom openai model

### PR DESCRIPTION
**Pull request by gianpaj**
## Related ISSUE
https://github.com/Zhengqbbb/cz-git/issues/153

## Type Of Change

- [x] ✨ New feature (non-breaking change which adds functionality)

How do I test this? I tried to build but now I don't know how to run `cz-git` or `czg ai`

### CODE REVIEW

**Comment by Zhengqbbb** [comment]
> How do I test this? I tried to build but now I don't know how to run `cz-git` or `czg ai`

1. Run command
```sh
pnpm build
# or
pnpm dev
```
2. Run command to debug or test result

- `cz-git` <sup>just plugin</sup> turn on the option `useAI`. Then run commitizen's `cz` command
- `czg` you can use `pnpm x` or `pnpm czg` to run exec `czg` exec file

https://github.com/Zhengqbbb/cz-git/assets/40693636/1d3eaa69-3a15-4ddc-84b9-37ef2031b760

**Comment by gianpaj** [comment]
@Zhengqbbb thanks for the video!

Can you check my last commit and debut it, please? I have the model setting in, but still doesn't work

```bash
$ cat ~/.config/.czrc
{"openAIToken":"sk-xxx","openAIModel":"gpt-4-1106-preview"}
```

```bash
$ pnpm x ai -a czg

> cz-git@1.8.0 x /Users/gianpaj/tmp/cz-git
> czg "ai" "-a" "czg"

czg@1.8.0

? Select the type of change that you're committing: feat:     A new feature
ℹ Generating your AI commit subject...
{ aiModel: undefined }
```

**Comment by Zhengqbbb** [comment]
> Can you check my last commit and debut it, please? I have the model setting in, but still doesn't work

```diff
- {"openAIToken":"sk-xxx","openAIModel":"gpt-4-1106-preview"}
+ {"openAIToken":"sk-xxx","aiModel":"gpt-4-1106-preview"}
```

image

**Comment by Zhengqbbb** [comment]
I have released a next pre-release version 🌟(**v1.10.0-beta.1**)🌟 for testing.
Plan for the official release on the weekend  🚀.

**Welcome to try it out! 👀 Let me know if there are still any issues. 🎉**

```sh
npm install -g czg@next
czg -v # ensure version is v1.10.0-beta.1
czg -h # show help

# Usage

### 1. Use the default `gpt-4o-mini` model
czg ai

### 2. Set specify a model in current session
czg ai -M=gpt-3.5-turbo

### 3. Setup the default model
czg --api-model="gpt-4"
```

See more setup details in https://deploy-preview-185--cz-git.netlify.app/recipes/openai#setup-openai-token

**Pull request closed without merging**
