### PR TITLE
fix(cli): fix pnpm fail to create bin on install

### PR DESCRIPTION
**Pull request by jrson83**
## Related ISSUE

None

## Type Of Change

- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 📝 Document (This change requires a documentation update)
- [ ] 🎨 Theme style (Theme style beautification)
- [ ] ⚠  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🔨 Workflow (Workflow changes)

## Clear Describe

fix: pnpm fail to create bin when running `pnpm install`

## Description

When running `pnpm install` in the repo root for the first time, pnpm can't create `node_modules\.bin` folders, cause they do not exist (cause they are not build yet) and throws warnings:

```bash
 WARN  Failed to create bin at D:\test\cz-git\node_modules\.bin\czg. The source file at D:\test\cz-git\node_modules\czg\bin\index.js does not exist.
 WARN  Failed to create bin at D:\test\cz-git\node_modules\.bin\git-czg. The source file at D:\test\cz-git\node_modules\czg\bin\index.js does not exist.
```

## Test Case

No need for additional test case.

### CODE REVIEW

**Comment by Zhengqbbb** [comment]
@jrson83 LGTM. 🚀 But current in my other repo has not been reproduced yet.
I have been release a next version `1.6.1-beta.1` to provide your. Please have a try, let me known is that have any ISSUE.

```sh
pnpm install czg@next 
```

**Comment by jrson83** [comment]
> @jrson83 LGTM. 🚀 But current in my other repo has not been reproduced yet. I have been release a next version `1.6.1-beta.1` to provide your. Please have a try, let me known is that have any ISSUE.
> 
> ```shell
> pnpm install -D czg@next 
> ```

@Zhengqbbb I did not have any issues when installing the NPM package with pnpm. The issue exists only in the cz-git monorepo.

To reproduce:

```bash
git clone https://github.com/Zhengqbbb/cz-git.git
cd cz-git
pnpm install
```

Then you should see the console warnings.

**Comment by Zhengqbbb** [comment]
I thought it had an impact on your project, so it this is directed at my project is it lol. thx 🤣
Actually I'd like to know if `czg` is working properly in your project, I'd like to know if working well in windows ?

**Comment by jrson83** [comment]
@Zhengqbbb Ah okay 😁 Yeah it is working very well on windows and I like it very much cause it has so small install size!

The only issue I had was related to husky/prepare-commit-msg hook. Cause windows terminal does not support interaction, I use the following workaround to run czg in a new terminal when running `git commit`:

```bash
#!/usr/bin/env sh

FILE=commit.cmd
if test -f "$FILE"; then
    echo "$FILE exists."
    rm commit.cmd
    exit 0;
fi
case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        echo "npx czg && exit" > commit.cmd
        start commit.cmd
    exit 1;
esac
. "$(dirname "$0")/_/husky.sh"
exec < /dev/tty && npx czg --hook || true
```

**Comment by Zhengqbbb** [comment]
> The only issue I had was related to husky/prepare-commit-msg hook. Cause windows terminal does not support interaction, I use the following workaround to run czg in a new terminal when running `git commit`:

So you handled show editor after `czg` interaction end ?

**Comment by Zhengqbbb** [comment]
> > > The only issue I had was related to husky/prepare-commit-msg hook. Cause windows terminal does not support interaction, I use the following workaround to run czg in a new terminal when running `git commit`:
> > 
> > 
> > So you handled show editor after `czg` interaction end ?
> 
> No 😁 before running `czg` it checks if the terminal is interactive. If not (windows), it opens a new terminal and runs `czg` inside. If you want to read more about, here is the [issue](https://github.com/commitizen/cz-cli/issues/627) at husky.

lol OK ~ there are only way you can hide editor. Alias your git command
- when you use `git commit` will use `git commit -m ''`
- But I don't known work well on windows. I am a POSIX SHELL developer

Follow this thread #87

add .bashrc or .zshrc
```bash
git() {
  local _cmd="$*"
  if [ "$1" = "commit" ] && [ "${_cmd%%"--help"}" = "$_cmd"  ]; then
    shift 1; command git commit -m ''
  else
    command git "$@"
  fi
}
```


Anyway thx your support and point out the problem 🤜 🤛

**Comment by jrson83** [comment]
> Anyway thx your support and point out the problem 🤜 🤛

No problem :grin: You gonna merge the PR? I gonna do another after.

**Comment by Zhengqbbb** [comment]
> > > The only issue I had was related to husky/prepare-commit-msg hook. Cause windows terminal does not support interaction, I use the following workaround to run czg in a new terminal when running `git commit`:
> > 
> > 
> > So you handled show editor after `czg` interaction end ?
> 
> No 😁 before running `czg` it checks if the terminal is interactive. If not (windows), it opens a new terminal and runs `czg` inside. If you want to read more about, here is the [issue](https://github.com/commitizen/cz-cli/issues/627) at husky.

@jrson83  !!!

https://github.com/Zhengqbbb/cz-git/issues/87#issuecomment-1982847003



```sh
git config core.editor cat
git commit # try it !
```

**Pull request merged**
