### PR TITLE
refactor: improve build- and typescript configuration

### PR DESCRIPTION
**Pull request by jrson83**
## Related ISSUE

None

## Type Of Change

- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 📝 Document (This change requires a documentation update)
- [ ] 🎨 Theme style (Theme style beautification)
- [x] ⚠  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🔨 Workflow (Workflow changes)

## Clear Describe

refactor(workspace): improve build- and typescript configuration

## Description

There are several solutions to properly set up a monorepo with TypeScript or not. Since this is not already hard enough, bundlers put additional obstacles in your way.

There are issues with both `tsup` and `unbuild` when trying to use TypeScript project references. This can probably be traced back to the rollup dts plugin. Some of these issues have existed for several years. However, another approach is to use path aliases. There are also some things to consider like isolated packages but shared type definitions.

I am very happy with czg and would like to make a contribution here to improve the performance of the build scripts. Since I have been working a lot on setting up monorepos lately, I think I can make a useful contribution here.

### What does this PR change?

- reduce configuration files overhead
- reduce build scripts overhead
- improve build time performance (from around 20 to 6 seconds)
- improve `pnpm-workspace.yaml`
- add package.json `exports` and `TypeVersions`, fixes package imports, so they reference to source files (instead of `dist`)
- fix `tsup` to properly build dts (instead of using tsc)
- fix `tsup` packages build order auto discover
- fix lockfile after applying changes

I have tested different approaches, am very happy with this one and hope you like it too. Surely there is still something to improve. Let me know!

Please have a look at the scripts folder and the dev scripts of the package.json. I may have overlooked something.

## Test Case

No need for additional test case.

### CODE REVIEW

**Comment by Zhengqbbb** [comment]
WOW, thanks and understand your thoughts, you can tell me when you are ready.

But for now I have to talk about my design, why my build process is more complicated and why use `tsc`.

There are two parts here: the `core plugin` and the `result application`

The core plug-in is not required to be small, but to be fully compiled with d.ts may even cover completely. This will ensure that my subsequent application of bundle

And bundle is also the same need to pay attention to, cz-git is required with d.ts, while czg is the maximum compression bundle. so I am first cz-git compile once and then czg. so czg can get the maximum static analysis. Finally, cz-git is compressed again

This is the best way to reduce bundle application with **invisible errors** (which is important so I discarded speed) and `czg` and `cz-git` will get perfect static analysis

```
tsc plugins -> tsc cz-git -> tsup czg -> tsup cz-git -> tsup plugins
```

I can discard speed in packaging, but definitely not compile bundle out an application with problems

**Comment by jrson83** [comment]
Ah Okay I understand.

So on the current monorepo, imports are not resolved from source files (`.ts`) but instead of the compiled `lib` (`.js` & `.d.ts`). You first have to run `build` once to have working vscode IntelliSense support. In an optimal state, properly configured IntelliSense and auto-completion should lead to a more secure and reliable end result than imports from compiled files, I think. What do you think about this?

>  you can tell me when you are ready.

It is ready for now, please check out the changes and let me know what you think :)

**Comment by jrson83** [comment]
The build fails cause node 14 does not support spread syntax in tsup.config. Thats why I replaced it with `Object.assign`.

**Comment by Zhengqbbb** [comment]
> The build fails cause node 14 does not support spread syntax in tsup.config. Thats why I replaced it with `Object.assign`.

Thx ~

**Comment by Zhengqbbb** [comment]
@jrson83 
Github action status is shot down. Wait fix and ready to merge.

I have release v1.6.2-beta.3. I test in Node v12 docker is ok. you can have a try now~

**Comment by jrson83** [comment]
@Zhengqbbb great, thx! I will test the release on windows and I will try fix the Github action.

**Comment by Zhengqbbb** [comment]
wait for github team fix
https://twitter.com/githubstatus/status/1641091847735975937

**Comment by jrson83** [comment]
`build` and `test` from branch running with success on windows 11.

**Comment by Zhengqbbb** [comment]
@jrson83 Thanks your great work again 🤜✨🤛

**Pull request merged**
