### PR TITLE
fix: use proper spelling of `prefixes`

### PR DESCRIPTION
**Pull request by chrisbbreuer**
Thanks so much for this great tool! 🙂

I just started implementing it into our Stacks Framework and noticed `prefixes` was misspelt. I noticed because cspell told me haha

I would appreciate it if someone could take a look at this and let me know if there are any changes that would additionally need to be made.

Thanks!

### CODE REVIEW

**Comment by Zhengqbbb** [comment]
Thx ~ BREAKING CHANGES
I have to stop and check these name
If you find other irregularities, please point them out again

**Comment by Zhengqbbb** [comment]
@chrisbbreuer 

After a morning of reflection.
**IMHO, I will say no to modify prefixes spelling.**
I have to be accountable to other people currently using my library. There are too many places to modify once passed.

But no doubt I made a mistake. I did not pay attention to naming you. I will pay more attention in the future.

If you have any other questions, you can tell to me, but at the same time I hope you can understand my decision, sorry.

Thank you for your support and work❤️

**Comment by chrisbbreuer** [comment]
Completely understood. And yea, this certainly is a breaking change. Thanks for considering.

**Comment by Zhengqbbb** [comment]
@chrisbbreuer 
Thank you very much for pointing that out. If I need a major version update in the future. I will seriously fix it.

**Comment by Zhengqbbb** [comment]
Hi @chrisbbreuer !
The latest version 🌟(v1.4.0)🌟 should be resolve this request , please have a try. 💪
👀 Let me know if there are still any issues. Thanks for you work and support! 🎉


* **cz-git,czg:** main fix `issuePrefixs` typo field
  * Current version has been already processed for **normal compatibility**

```diff
{
  message: {
-   footerPrefixsSelect
+   footerPrefixesSelect

-   customFooterPrefixs
+   customFooterPrefix
 }

-   issuePrefixs
+   issuePrefixes

-   customIssuePrefixsAlign
+   customIssuePrefixAlign

-   emptyIssuePrefixsAlias
+   emptyIssuePrefixAlias

-   customIssuePrefixsAlias
+   customIssuePrefixAlias

-   allowCustomIssuePrefixs
+   allowCustomIssuePrefix

-   allowEmptyIssuePrefixs
+   allowEmptyIssuePrefix
}
```

**Comment by chrisbbreuer** [comment]
Thank you very much! I will get it implemented into [Stacks](github.com/stacksjs/stacks) framework this week 😊

**Pull request closed without merging**
